
name: 'Node Red Flow'
description: 'Select a node-red contrib repo to update'
inputs:
  repo:
    description: 'Repo to update'
    required: true
    default: 'node-red-contrib-discord'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}